# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-16 19:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('establishments', '0006_auto_20160516_2139'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0004_auto_20160330_0322'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_username', models.CharField(blank=True, max_length=50)),
                ('facebook_username', models.CharField(blank=True, max_length=50)),
                ('twitter_username', models.CharField(blank=True, max_length=15)),
                ('fav_artists', models.TextField()),
                ('fav_genres', models.TextField()),
                ('check_ins', models.ManyToManyField(related_name='checked_in_at', to='establishments.Establishment')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_of', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
