# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-16 20:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='check_ins',
        ),
    ]
