# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-21 04:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20160516_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='fav_artists',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fav_genres',
            field=models.TextField(blank=True),
        ),
    ]
