# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-04 23:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('establishments', '0004_auto_20160409_2116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_url', models.URLField(blank=True)),
                ('establishment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='playlist', to='establishments.Establishment')),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_uri', models.CharField(max_length=36)),
                ('votes', models.IntegerField(default=0)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='polls.Playlist')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='track',
            unique_together=set([('playlist', 'spotify_uri')]),
        ),
    ]
