# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-06 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='track',
        ),
        migrations.AddField(
            model_name='track',
            name='votes',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
