# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-08 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_track_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='duration',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
