# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-27 01:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20160406_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='establishment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='playlist', to='establishments.Establishment'),
        ),
    ]
