# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-27 14:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20160427_0330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='url',
            new_name='purl',
        ),
        migrations.RenameField(
            model_name='track',
            old_name='url',
            new_name='turl',
        ),
        migrations.AlterUniqueTogether(
            name='track',
            unique_together=set([('playlist', 'turl')]),
        ),
    ]
