# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-11 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_remove_track_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='original_creator',
            field=models.CharField(default='spotify', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playlist',
            name='original_spotify_url',
            field=models.URLField(default='https://open.spotify.com/user/spotify/playlist/75dwLdmL07hDEDWqX17QeE', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='track',
            name='requested',
            field=models.BooleanField(default=False),
        ),
    ]
