# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-27 17:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_playlist_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='purl',
            new_name='link',
        ),
        migrations.RenameField(
            model_name='track',
            old_name='turl',
            new_name='link',
        ),
        migrations.AlterUniqueTogether(
            name='track',
            unique_together=set([('playlist', 'link')]),
        ),
    ]
