# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-11 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20160511_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='original_creator',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='original_spotify_url',
            field=models.URLField(blank=True, max_length=100),
        ),
    ]
