# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-16 19:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile'),
        ('polls', '0006_auto_20160511_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='request_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requested_by', to='users.Profile'),
        ),
        migrations.AddField(
            model_name='track',
            name='voters',
            field=models.ManyToManyField(related_name='voted_by', to='users.Profile'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='establishment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_of', to='establishments.Establishment'),
        ),
        migrations.AlterField(
            model_name='track',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_of', to='polls.Playlist'),
        ),
    ]
