# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-27 17:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20160427_1915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='link',
            new_name='spotify_url',
        ),
        migrations.RenameField(
            model_name='track',
            old_name='link',
            new_name='spotify_url',
        ),
        migrations.AlterUniqueTogether(
            name='track',
            unique_together=set([('playlist', 'spotify_url')]),
        ),
    ]
