# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-16 19:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20160516_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='request_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requested_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='track',
            name='voters',
            field=models.ManyToManyField(related_name='voted_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
