# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-16 20:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20160516_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='requested',
        ),
        migrations.AlterField(
            model_name='playlist',
            name='establishment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='establishment', to='establishments.Establishment'),
        ),
        migrations.AlterField(
            model_name='track',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_of', to='polls.Playlist'),
        ),
        migrations.AlterField(
            model_name='track',
            name='request_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requested', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='track',
            name='voters',
            field=models.ManyToManyField(related_name='voted', to=settings.AUTH_USER_MODEL),
        ),
    ]
