# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-01 01:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_playlist_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='owner',
        ),
    ]
