# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-01 02:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_remove_playlist_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='spotify_url',
            field=models.URLField(blank=True),
        ),
    ]
