# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-18 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20160516_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='explicit_lyrics',
            field=models.BooleanField(default=False),
        ),
    ]
