# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-10 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_auto_20160904_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='in_playlist',
            field=models.BooleanField(default=True),
        ),
    ]
