# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-11 19:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_auto_20160910_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='establishment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='establishment_playlist', to='establishments.Establishment'),
        ),
    ]
