# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-12 01:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_auto_20160911_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='spotify_uri',
            field=models.CharField(max_length=200),
        ),
    ]
