# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-16 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_auto_20160912_0332'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='cover_image_url',
            field=models.CharField(default='https://i.scdn.co/image/611075a194bd41992f62f41b9bb4d1fb956e1235', max_length=200),
            preserve_default=False,
        ),
    ]
