# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-30 01:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishment',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='country',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='postcode',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='street',
            field=models.CharField(max_length=100),
        ),
    ]
