# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-09 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0002_auto_20160330_0308'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishment',
            name='spotify_username',
            field=models.CharField(default='my_spotify_username', max_length=100),
            preserve_default=False,
        ),
    ]
