# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-09 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0003_establishment_spotify_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='establishment',
            name='number',
        ),
        migrations.RemoveField(
            model_name='establishment',
            name='street',
        ),
        migrations.AddField(
            model_name='establishment',
            name='address',
            field=models.CharField(default='Carrer Pelai, 14', max_length=100),
            preserve_default=False,
        ),
    ]
