# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-16 19:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0005_establishment_lastfm_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishment',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='establishments_of', to=settings.AUTH_USER_MODEL),
        ),
    ]
