# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-16 20:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('establishments', '0006_auto_20160516_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishment',
            name='check_ins',
            field=models.ManyToManyField(related_name='checked_in', to=settings.AUTH_USER_MODEL),
        ),
    ]
