# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-04 20:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0008_auto_20160516_2258'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='establishment',
            options={'ordering': ('name', 'country', 'city')},
        ),
    ]
